// Input : 
// the output skim root file of tWIHEPFramework
// Function: 
// select prompt MC fake events according to Regions/Postfix and save/reconstruct only interested branches
// mcMatching prompt right charge: leadLep_isMatchRightCharge && leadLep_mcPromptFS && secondLep_isMatchRightCharge && secondLep_mcPromptFS  
// same sign lepton : fabs(Sum2lCharge)==2 
// dilep are not tight tight: Dilep_nTight < 2 
//      Region cuts : 
//      SigRegion: n_presel_jets >=4
//      ttWctrl: n_presel_jets ==3
//      NoJetNCut: ""
// Output:
// rootplas for plotting and statistics study

#include "function.C"
// options
Bool_t _useFakeRate = true; // set to true if we recalculate FakeRate Weighting.

void SetOldTreeBranchStatus(TTree* readtree);

//Fake Rate
//Histograms that are used for applying lepton fake rate weight
std::vector<std::string> _frSystNames = {"central","up","down","pt1","pt2","be1","be2","QCD","TT"};
TString fakeRateFileName = "/publicfs/cms/data/TopQuark/cms13TeV/Binghuan/tWIHEPFramework/config/weights/ttH2018/FR_data_ttH_mva.root";
TString fakeRateMuonHistName = "FR_mva090_mu_data_comb";
TString fakeRateElectronHistName = "FR_mva090_el_data_comb_NC";
std::map<std::string,TH2F*> _MuonFakeRate;
std::map<std::string,TH2F*> _ElectronFakeRate;

void Rootplas_Prompt_fake(TString InputDir, TString OutputDir, TString FileName, TString Postfix){

    if(Postfix!="SigRegion" && Postfix!="ttWctrl" && Postfix!="NoJetNCut"){
        std::cout<< " ##################  ERROR ############ "<<std::endl;
        std::cout<< " Postfix must be SigRegion,ttWctrl or NoJetNCut, please pass a correct Postfix "<< std::endl;
        return;
    }
    TString Input = InputDir +"/"+ FileName + "Skim.root";
    TString Output = OutputDir  +"/"+FileName+ "_Promptfake_"+Postfix+".root";
    std::cout <<" inpupt file is " << Input << std::endl;
    std::cout <<" outpupt file is " << Output << std::endl;
    
    // fake rate  
    if (_useFakeRate){
        for (auto const frSystName: _frSystNames){
            setFakeRateHistograms(fakeRateFileName, fakeRateMuonHistName, fakeRateElectronHistName, _MuonFakeRate, _ElectronFakeRate, frSystName, frSystName);
        }
    }
    
    TFile *oldfile = new TFile(Input);
    TTree *oldtree = (TTree*)oldfile->Get("TNT/BOOM");


    Long64_t nentries = oldtree->GetEntries(); 
    
    int nLooseJet=0;
    int HiggsDecay=0;
    double rtrueInteractions=0;
    int rnBestVtx=0;
    Long64_t nEvt = 0;
    Long64_t nEvent = 0;
   
    float firstLep_mcPromptGamma(0.), secondLep_mcPromptGamma(0.), thirdLep_mcPromptGamma(0.);
    float firstLep_mcPromptFS(0.), secondLep_mcPromptFS(0.), thirdLep_mcPromptFS(0.);
    float firstLep_isMatchRightCharge(0.), secondLep_isMatchRightCharge(0.), thirdLep_isMatchRightCharge(0.);
    float lep1_pdgId(0.), lep2_pdgId(0.), lep3_pdgId(0.);
    float lep1_conept(0.), lep2_conept(0.);// lep3_conept(0.);
    float lep1_ismvasel(0.), lep2_ismvasel(0.), lep3_ismvasel(0.);
    float lep1_eta(0.), lep2_eta(0.), lep3_eta(0.);
    float Sum2lCharge(0.), Dilep_nTight(0.), massL_SFOS(0.), Trilep_nTight(0.), Dilep_pdgId(0.), Sum3LCharge(0.);
    float xsec_rwgt(0.);
    float mvaOutput_2lss_ttV(0.), mvaOutput_2lss_ttbar(0.);
    float EventWeight(0.), FakeRate(0.);
    float FakeRate_m_central(0.), FakeRate_m_up(0.), FakeRate_m_down(0.), FakeRate_m_pt1(0.), FakeRate_m_pt2(0.), FakeRate_m_be1(0.), FakeRate_m_be2(0.), FakeRate_m_QCD(0.), FakeRate_m_TT(0.); 
    float FakeRate_e_central(0.), FakeRate_e_up(0.), FakeRate_e_down(0.), FakeRate_e_pt1(0.), FakeRate_e_pt2(0.), FakeRate_e_be1(0.), FakeRate_e_be2(0.), FakeRate_e_QCD(0.), FakeRate_e_TT(0.); 

    oldtree->SetBranchAddress("trueInteractions", &rtrueInteractions);
    oldtree->SetBranchAddress("nBestVtx", &rnBestVtx);
    oldtree->SetBranchAddress("Jet_numLoose", &nLooseJet);
    oldtree->SetBranchAddress("HiggsDecay", &HiggsDecay);
    oldtree->SetBranchAddress("lep1_pdgId", &lep1_pdgId);
    oldtree->SetBranchAddress("lep2_pdgId", &lep2_pdgId);
    oldtree->SetBranchAddress("lep3_pdgId", &lep3_pdgId);
    oldtree->SetBranchAddress("leadLep_corrpt", &lep1_conept);
    oldtree->SetBranchAddress("secondLep_corrpt", &lep2_conept);
    //oldtree->SetBranchAddress("thirdLep_corrpt", &lep3_conept);
    oldtree->SetBranchAddress("lep1_ismvasel", &lep1_ismvasel);
    oldtree->SetBranchAddress("lep2_ismvasel", &lep2_ismvasel);
    oldtree->SetBranchAddress("lep3_ismvasel", &lep3_ismvasel);
    oldtree->SetBranchAddress("lep1_eta", &lep1_eta);
    oldtree->SetBranchAddress("lep2_eta", &lep2_eta);
    oldtree->SetBranchAddress("lep3_eta", &lep3_eta);
    oldtree->SetBranchAddress("leadLep_mcPromptGamma", &firstLep_mcPromptGamma);
    oldtree->SetBranchAddress("secondLep_mcPromptGamma", &secondLep_mcPromptGamma);
    oldtree->SetBranchAddress("thirdLep_mcPromptGamma", &thirdLep_mcPromptGamma);
    oldtree->SetBranchAddress("leadLep_mcPromptFS", &firstLep_mcPromptFS);
    oldtree->SetBranchAddress("secondLep_mcPromptFS", &secondLep_mcPromptFS);
    oldtree->SetBranchAddress("thirdLep_mcPromptFS", &thirdLep_mcPromptFS);
    oldtree->SetBranchAddress("leadLep_isMatchRightCharge", &firstLep_isMatchRightCharge);
    oldtree->SetBranchAddress("secondLep_isMatchRightCharge", &secondLep_isMatchRightCharge);
    oldtree->SetBranchAddress("thirdLep_isMatchRightCharge", &thirdLep_isMatchRightCharge);
    oldtree->SetBranchAddress("Sum2lCharge", &Sum2lCharge);
    oldtree->SetBranchAddress("Sum3LCharge", &Sum3LCharge);
    oldtree->SetBranchAddress("Dilep_nTight", &Dilep_nTight);
    oldtree->SetBranchAddress("Dilep_pdgId", &Dilep_pdgId);
    oldtree->SetBranchAddress("massL_SFOS", &massL_SFOS);
    oldtree->SetBranchAddress("Trilep_nTight", &Trilep_nTight);
    oldtree->SetBranchAddress("nEvent", &nEvent);
    oldtree->SetBranchAddress("mvaOutput_2lss_ttV", &mvaOutput_2lss_ttV);
    oldtree->SetBranchAddress("mvaOutput_2lss_ttbar", &mvaOutput_2lss_ttbar);
    oldtree->SetBranchAddress("EventWeight", &EventWeight);
    oldtree->SetBranchAddress("FakeRate", &FakeRate);
    oldtree->SetBranchAddress("FakeRate_m_central", &FakeRate_m_central);
    oldtree->SetBranchAddress("FakeRate_m_up", &FakeRate_m_up);
    oldtree->SetBranchAddress("FakeRate_m_down", &FakeRate_m_down);
    oldtree->SetBranchAddress("FakeRate_m_pt1", &FakeRate_m_pt1);
    oldtree->SetBranchAddress("FakeRate_m_pt2", &FakeRate_m_pt2);
    oldtree->SetBranchAddress("FakeRate_m_be1", &FakeRate_m_be1);
    oldtree->SetBranchAddress("FakeRate_m_be2", &FakeRate_m_be2);
    oldtree->SetBranchAddress("FakeRate_m_QCD", &FakeRate_m_QCD);
    oldtree->SetBranchAddress("FakeRate_m_TT", &FakeRate_m_TT);
    oldtree->SetBranchAddress("FakeRate_e_central", &FakeRate_e_central);
    oldtree->SetBranchAddress("FakeRate_e_up", &FakeRate_e_up);
    oldtree->SetBranchAddress("FakeRate_e_down", &FakeRate_e_down);
    oldtree->SetBranchAddress("FakeRate_e_pt1", &FakeRate_e_pt1);
    oldtree->SetBranchAddress("FakeRate_e_pt2", &FakeRate_e_pt2);
    oldtree->SetBranchAddress("FakeRate_e_be1", &FakeRate_e_be1);
    oldtree->SetBranchAddress("FakeRate_e_be2", &FakeRate_e_be2);
    oldtree->SetBranchAddress("FakeRate_e_QCD", &FakeRate_e_QCD);
    oldtree->SetBranchAddress("FakeRate_e_TT", &FakeRate_e_TT);

    SetOldTreeBranchStatus(oldtree);
    
    //TFile *newfile = new TFile("IHEP_test.root","recreate");
    TFile *newfile = new TFile(Output,"recreate");
    TTree *newtree = new TTree("syncTree","syncTree");
    

    float trueInteractions=0;
    float nBestVtx=0;
    float Jet_numLoose=0;
    // shape theoretical uncertainties 
    float CMS_ttHl_thu_shape_ttH(0.), CMS_ttHl_thu_shape_ttH_SysUp(0.), CMS_ttHl_thu_shape_ttH_SysDown(0.);
    float CMS_ttHl_thu_shape_ttW(0.), CMS_ttHl_thu_shape_ttW_SysUp(0.), CMS_ttHl_thu_shape_ttW_SysDown(0.);
    float CMS_ttHl_thu_shape_ttZ(0.), CMS_ttHl_thu_shape_ttZ_SysUp(0.), CMS_ttHl_thu_shape_ttZ_SysDown(0.);
    // closure shape uncertainties
    float CMS_ttHl17_Clos_e_shape_ee(0.), CMS_ttHl17_Clos_e_shape_ee_SysUp(0.), CMS_ttHl17_Clos_e_shape_ee_SysDown(0.);
    float CMS_ttHl17_Clos_e_shape_em(0.), CMS_ttHl17_Clos_e_shape_em_SysUp(0.), CMS_ttHl17_Clos_e_shape_em_SysDown(0.);
    float CMS_ttHl17_Clos_m_shape_mm(0.), CMS_ttHl17_Clos_m_shape_mm_SysUp(0.), CMS_ttHl17_Clos_m_shape_mm_SysDown(0.);
    float CMS_ttHl17_Clos_m_shape_em(0.), CMS_ttHl17_Clos_m_shape_em_SysUp(0.), CMS_ttHl17_Clos_m_shape_em_SysDown(0.);

    newtree = oldtree->CloneTree(0);
    newtree->Branch("TrueInteractions", &trueInteractions);
    newtree->Branch("nBestVTX", &nBestVtx);
    newtree->Branch("nEvt", &nEvt);
    newtree->Branch("xsec_rwgt", &xsec_rwgt);
    newtree->Branch("nLooseJet", &Jet_numLoose);
    newtree->Branch("CMS_ttHl_thu_shape_ttH", &CMS_ttHl_thu_shape_ttH);
    newtree->Branch("CMS_ttHl_thu_shape_ttH_SysUp", &CMS_ttHl_thu_shape_ttH_SysUp);
    newtree->Branch("CMS_ttHl_thu_shape_ttH_SysDown", &CMS_ttHl_thu_shape_ttH_SysDown);
    newtree->Branch("CMS_ttHl_thu_shape_ttW", &CMS_ttHl_thu_shape_ttW);
    newtree->Branch("CMS_ttHl_thu_shape_ttW_SysUp", &CMS_ttHl_thu_shape_ttW_SysUp);
    newtree->Branch("CMS_ttHl_thu_shape_ttW_SysDown", &CMS_ttHl_thu_shape_ttW_SysDown);
    newtree->Branch("CMS_ttHl_thu_shape_ttZ", &CMS_ttHl_thu_shape_ttZ);
    newtree->Branch("CMS_ttHl_thu_shape_ttZ_SysUp", &CMS_ttHl_thu_shape_ttZ_SysUp);
    newtree->Branch("CMS_ttHl_thu_shape_ttZ_SysDown", &CMS_ttHl_thu_shape_ttZ_SysDown);
    newtree->Branch("CMS_ttHl17_Clos_e_shape_ee", &CMS_ttHl17_Clos_e_shape_ee);
    newtree->Branch("CMS_ttHl17_Clos_e_shape_ee_SysUp", &CMS_ttHl17_Clos_e_shape_ee_SysUp);
    newtree->Branch("CMS_ttHl17_Clos_e_shape_ee_SysDown", &CMS_ttHl17_Clos_e_shape_ee_SysDown);
    newtree->Branch("CMS_ttHl17_Clos_e_shape_em", &CMS_ttHl17_Clos_e_shape_em);
    newtree->Branch("CMS_ttHl17_Clos_e_shape_em_SysUp", &CMS_ttHl17_Clos_e_shape_em_SysUp);
    newtree->Branch("CMS_ttHl17_Clos_e_shape_em_SysDown", &CMS_ttHl17_Clos_e_shape_em_SysDown);
    newtree->Branch("CMS_ttHl17_Clos_m_shape_mm", &CMS_ttHl17_Clos_m_shape_mm);
    newtree->Branch("CMS_ttHl17_Clos_m_shape_mm_SysUp", &CMS_ttHl17_Clos_m_shape_mm_SysUp);
    newtree->Branch("CMS_ttHl17_Clos_m_shape_mm_SysDown", &CMS_ttHl17_Clos_m_shape_mm_SysDown);
    newtree->Branch("CMS_ttHl17_Clos_m_shape_em", &CMS_ttHl17_Clos_m_shape_em);
    newtree->Branch("CMS_ttHl17_Clos_m_shape_em_SysUp", &CMS_ttHl17_Clos_m_shape_em_SysUp);
    newtree->Branch("CMS_ttHl17_Clos_m_shape_em_SysDown", &CMS_ttHl17_Clos_m_shape_em_SysDown);
    
    
    //newtree = oldtree->CopyTree("jet4_pt>=30");
    
    for (Long64_t i=0;i<nentries; i++) {
        trueInteractions = -999;
        Jet_numLoose = -999;
        nBestVtx = -999;
        nEvt = -999;
        xsec_rwgt = 1.;
        oldtree->GetEntry(i);
        Bool_t pass2LMatchRightCharge = kTRUE;
        Bool_t pass2LPromptFS = kTRUE;
        Bool_t pass2LCharge = kTRUE;
        Bool_t pass2LTightID = kTRUE;
        Bool_t pass2LRegionCut = kTRUE;
        Bool_t passCut = kFALSE;
        if(!(firstLep_mcPromptFS==1 && secondLep_mcPromptFS==1))pass2LPromptFS = kFALSE;
        if(!(firstLep_isMatchRightCharge==1 && secondLep_isMatchRightCharge==1))pass2LMatchRightCharge = kFALSE;
        if(!(fabs(Sum2lCharge)==2))pass2LCharge = kFALSE;
        if(!(Dilep_nTight <2))pass2LTightID = kFALSE;
        if(Postfix=="SigRegion" && nLooseJet <4)pass2LRegionCut = kFALSE;
        if(Postfix=="ttWctrl" && nLooseJet !=3)pass2LRegionCut = kFALSE;
        passCut = pass2LMatchRightCharge && pass2LPromptFS && pass2LCharge && pass2LTightID && pass2LRegionCut;
    
        if(passCut){
            trueInteractions = rtrueInteractions;
            nBestVtx = rnBestVtx;
            nEvt = nEvent;
            xsec_rwgt = get_rewgtlumi(FileName);
            Jet_numLoose = nLooseJet;
            if (nEvent <0) nEvt = nEvent + 4294967296; // 4294967296 = 2^32, this is to fix the problem saving EVENT_event as a wrong type
            else nEvt = nEvent;
            // fill lnN1D_p1()
            // https://github.com/peruzzim/cmgtools-lite/blob/94X_dev_ttH/TTHAnalysis/python/plotter/ttH-multilepton/systsUnc.txt
            CMS_ttHl_thu_shape_ttH = 1.;
            CMS_ttHl_thu_shape_ttH_SysUp = lnN1D_p1(1.05, mvaOutput_2lss_ttbar, -1, 1) * lnN1D_p1(1.02, mvaOutput_2lss_ttV, -1, 1)/1.04;
            CMS_ttHl_thu_shape_ttH_SysDown = 1./CMS_ttHl_thu_shape_ttH_SysUp;
            CMS_ttHl_thu_shape_ttW = 1.;
            CMS_ttHl_thu_shape_ttW_SysUp = lnN1D_p1(1.02, mvaOutput_2lss_ttbar, -1, 1) * lnN1D_p1(1.03, mvaOutput_2lss_ttV, -1, 1)/1.04;
            CMS_ttHl_thu_shape_ttW_SysDown = 1./CMS_ttHl_thu_shape_ttW_SysUp;
            CMS_ttHl_thu_shape_ttZ = 1.;
            CMS_ttHl_thu_shape_ttZ_SysUp = lnN1D_p1(1.06, mvaOutput_2lss_ttbar, -1, 1) * lnN1D_p1(1.06, mvaOutput_2lss_ttV, -1, 1)/1.04;
            CMS_ttHl_thu_shape_ttZ_SysDown = 1./CMS_ttHl_thu_shape_ttZ_SysUp;
            CMS_ttHl17_Clos_e_shape_ee = 1.;
            CMS_ttHl17_Clos_e_shape_ee_SysUp = lnN1D_p1(1.5, mvaOutput_2lss_ttbar, -1, 1)/1.2;
            CMS_ttHl17_Clos_e_shape_ee_SysDown = 1./CMS_ttHl17_Clos_e_shape_ee_SysUp;
            CMS_ttHl17_Clos_e_shape_em = 1.;
            CMS_ttHl17_Clos_e_shape_em_SysUp = lnN1D_p1(1.25, mvaOutput_2lss_ttbar, -1, 1)/1.1;
            CMS_ttHl17_Clos_e_shape_em_SysDown = 1./CMS_ttHl17_Clos_e_shape_em_SysUp;
            CMS_ttHl17_Clos_m_shape_mm = 1.;
            CMS_ttHl17_Clos_m_shape_mm_SysUp = lnN1D_p1(1.5, mvaOutput_2lss_ttV, -1, 1)/1.24;
            CMS_ttHl17_Clos_m_shape_mm_SysDown = 1./CMS_ttHl17_Clos_m_shape_mm_SysUp;
            CMS_ttHl17_Clos_m_shape_em = 1.;
            CMS_ttHl17_Clos_m_shape_em_SysUp = lnN1D_p1(1.8, mvaOutput_2lss_ttV, -1, 1)/1.35;
            CMS_ttHl17_Clos_m_shape_em_SysDown = 1./CMS_ttHl17_Clos_m_shape_em_SysUp;
           
            // FakeRate
            if(_useFakeRate){
                std::map<std::string,float> mFakeRate;
                std::map<std::string,float> eFakeRate;
                float old_FakeRate = FakeRate;
                FakeRate = getFakeRateWeight( lep1_ismvasel,  lep1_pdgId,  lep1_conept,  lep1_eta,  lep2_ismvasel,  lep2_pdgId,  lep2_conept,  lep2_eta , _MuonFakeRate, _ElectronFakeRate);
                for(auto const frSystName: _frSystNames){
                    mFakeRate[frSystName] = getFakeRateWeight(lep1_ismvasel,  lep1_pdgId,  lep1_conept,  lep1_eta,  lep2_ismvasel,  lep2_pdgId,  lep2_conept,  lep2_eta, _MuonFakeRate, _ElectronFakeRate, frSystName,"central"); 
                    eFakeRate[frSystName] = getFakeRateWeight(lep1_ismvasel,  lep1_pdgId,  lep1_conept,  lep1_eta,  lep2_ismvasel,  lep2_pdgId,  lep2_conept,  lep2_eta, _MuonFakeRate, _ElectronFakeRate, "central",frSystName); 
                }
                EventWeight *= FakeRate/old_FakeRate;
                FakeRate_m_central=mFakeRate["central"];
                FakeRate_m_up=mFakeRate["up"];
                FakeRate_m_down=mFakeRate["down"];
                FakeRate_m_pt1=mFakeRate["pt1"];
                FakeRate_m_pt2=mFakeRate["pt2"];
                FakeRate_m_be1=mFakeRate["be1"];
                FakeRate_m_be2=mFakeRate["be2"];
                FakeRate_m_TT=mFakeRate["TT"];
                FakeRate_m_QCD=mFakeRate["QCD"];
                FakeRate_e_central=eFakeRate["central"];
                FakeRate_e_up=eFakeRate["up"];
                FakeRate_e_down=eFakeRate["down"];
                FakeRate_e_pt1=eFakeRate["pt1"];
                FakeRate_e_pt2=eFakeRate["pt2"];
                FakeRate_e_be1=eFakeRate["be1"];
                FakeRate_e_be2=eFakeRate["be2"];
                FakeRate_e_TT=eFakeRate["TT"];
                FakeRate_e_QCD=eFakeRate["QCD"];
            }
            
            newtree->Fill();
        }
        HiggsDecay =0;
        lep1_pdgId=0;
        lep2_pdgId=0;
        lep3_pdgId=0;
        lep1_conept=0;
        lep2_conept=0;
        //lep3_conept=0;
        lep1_ismvasel=0;
        lep2_ismvasel=0;
        lep3_ismvasel=0;
        lep1_eta=0;
        lep2_eta=0;
        lep3_eta=0;
        firstLep_isMatchRightCharge=0;
        secondLep_isMatchRightCharge=0;
        thirdLep_isMatchRightCharge=0;
        firstLep_mcPromptGamma=0;
        secondLep_mcPromptGamma=0;
        thirdLep_mcPromptGamma=0;
        firstLep_mcPromptFS=0;
        secondLep_mcPromptFS=0;
        thirdLep_mcPromptFS=0;
        nLooseJet = 0;
        Sum2lCharge =0;
        Dilep_nTight =0;
        Dilep_pdgId =0;
        massL_SFOS =0;
        Trilep_nTight =0;
        mvaOutput_2lss_ttV=0;
        mvaOutput_2lss_ttbar=0;
        EventWeight=0;
        FakeRate=0;
        FakeRate_m_central=0;
        FakeRate_m_up=0;
        FakeRate_m_down=0;
        FakeRate_m_pt1=0;
        FakeRate_m_pt2=0;
        FakeRate_m_be1=0;
        FakeRate_m_be2=0;
        FakeRate_m_TT=0;
        FakeRate_m_QCD=0;
        FakeRate_e_central=0;
        FakeRate_e_up=0;
        FakeRate_e_down=0;
        FakeRate_e_pt1=0;
        FakeRate_e_pt2=0;
        FakeRate_e_be1=0;
        FakeRate_e_be2=0;
        FakeRate_e_TT=0;
        FakeRate_e_QCD=0;
    }

    newtree->SetName("syncTree");
    newtree->SetTitle("syncTree");
    //newtree->Write();
    newtree->AutoSave();
    gDirectory->Delete("BOOM;*");
    
    delete oldfile;    
    delete newfile;
}

void SetOldTreeBranchStatus(TTree* readtree){
   readtree->SetBranchStatus("*",0);
   /*
   //readtree->SetBranchStatus("pvertex_ndof",1);
   //readtree->SetBranchStatus("pvertex_z",1);
   //readtree->SetBranchStatus("pvertex_dxy",1);
   readtree->SetBranchStatus("mu1_pt",1);
   readtree->SetBranchStatus("mu1_conept",1);
   readtree->SetBranchStatus("mu1_eta",1);
   readtree->SetBranchStatus("mu1_phi",1);
   readtree->SetBranchStatus("mu1_E",1);
   readtree->SetBranchStatus("mu1_miniRelIso",1);
   readtree->SetBranchStatus("mu1_miniIsoCharged",1);
   readtree->SetBranchStatus("mu1_miniIsoNeutral",1);
   readtree->SetBranchStatus("mu1_jetPtRel",1);
   readtree->SetBranchStatus("mu1_jetPtRatio",1);
   readtree->SetBranchStatus("mu1_jetCSV",1);
   readtree->SetBranchStatus("mu1_sip3D",1);
   readtree->SetBranchStatus("mu1_dxyAbs",1);
   readtree->SetBranchStatus("mu1_dz",1);
   readtree->SetBranchStatus("mu1_segmentCompatibility",1);
   readtree->SetBranchStatus("mu1_leptonMVA",1);
   readtree->SetBranchStatus("mu1_dpt_div_pt",1);
   readtree->SetBranchStatus("mu2_pt",1);
   readtree->SetBranchStatus("mu2_conept",1);
   readtree->SetBranchStatus("mu2_eta",1);
   readtree->SetBranchStatus("mu2_phi",1);
   readtree->SetBranchStatus("mu2_E",1);
   readtree->SetBranchStatus("mu2_miniRelIso",1);
   readtree->SetBranchStatus("mu2_miniIsoCharged",1);
   readtree->SetBranchStatus("mu2_miniIsoNeutral",1);
   readtree->SetBranchStatus("mu2_jetPtRel",1);
   readtree->SetBranchStatus("mu2_jetPtRatio",1);
   readtree->SetBranchStatus("mu2_jetCSV",1);
   readtree->SetBranchStatus("mu2_sip3D",1);
   readtree->SetBranchStatus("mu2_dxyAbs",1);
   readtree->SetBranchStatus("mu2_dz",1);
   readtree->SetBranchStatus("mu2_segmentCompatibility",1);
   readtree->SetBranchStatus("mu2_leptonMVA",1);
   readtree->SetBranchStatus("mu2_dpt_div_pt",1);
   readtree->SetBranchStatus("ele1_pt",1);
   readtree->SetBranchStatus("ele1_conept",1);
   readtree->SetBranchStatus("ele1_eta",1);
   readtree->SetBranchStatus("ele1_phi",1);
   readtree->SetBranchStatus("ele1_E",1);
   readtree->SetBranchStatus("ele1_miniRelIso",1);
   readtree->SetBranchStatus("ele1_miniIsoCharged",1);
   readtree->SetBranchStatus("ele1_miniIsoNeutral",1);
   readtree->SetBranchStatus("ele1_jetPtRel",1);
   readtree->SetBranchStatus("ele1_jetPtRatio",1);
   readtree->SetBranchStatus("ele1_jetCSV",1);
   readtree->SetBranchStatus("ele1_sip3D",1);
   readtree->SetBranchStatus("ele1_dxyAbs",1);
   readtree->SetBranchStatus("ele1_dz",1);
   readtree->SetBranchStatus("ele1_ntMVAeleID",1);
   readtree->SetBranchStatus("ele1_leptonMVA",1);
   readtree->SetBranchStatus("ele2_pt",1);
   readtree->SetBranchStatus("ele2_conept",1);
   readtree->SetBranchStatus("ele2_eta",1);
   readtree->SetBranchStatus("ele2_phi",1);
   readtree->SetBranchStatus("ele2_E",1);
   readtree->SetBranchStatus("ele2_miniRelIso",1);
   readtree->SetBranchStatus("ele2_miniIsoCharged",1);
   readtree->SetBranchStatus("ele2_miniIsoNeutral",1);
   readtree->SetBranchStatus("ele2_jetPtRel",1);
   readtree->SetBranchStatus("ele2_jetPtRatio",1);
   readtree->SetBranchStatus("ele2_jetCSV",1);
   readtree->SetBranchStatus("ele2_sip3D",1);
   readtree->SetBranchStatus("ele2_dxyAbs",1);
   readtree->SetBranchStatus("ele2_dz",1);
   readtree->SetBranchStatus("ele2_ntMVAeleID",1);
   readtree->SetBranchStatus("ele2_leptonMVA",1);
   readtree->SetBranchStatus("mu1_mediumID",1);
   readtree->SetBranchStatus("mu1_isfakeablesel",1);
   readtree->SetBranchStatus("mu1_ismvasel",1);
   readtree->SetBranchStatus("mu2_mediumID",1);
   readtree->SetBranchStatus("mu2_isfakeablesel",1);
   readtree->SetBranchStatus("mu2_ismvasel",1);
   readtree->SetBranchStatus("ele1_isfakeablesel",1);
   readtree->SetBranchStatus("ele1_ismvasel",1);
   readtree->SetBranchStatus("ele1_isChargeConsistent",1);
   readtree->SetBranchStatus("ele1_passesConversionVeto",1);
   readtree->SetBranchStatus("ele2_isfakeablesel",1);
   readtree->SetBranchStatus("ele2_ismvasel",1);
   readtree->SetBranchStatus("ele2_isChargeConsistent",1);
   readtree->SetBranchStatus("ele2_passesConversionVeto",1);
   readtree->SetBranchStatus("mu1_charge",1);
   readtree->SetBranchStatus("mu1_jetNDauChargedMVASel",1);
   readtree->SetBranchStatus("mu2_charge",1);
   readtree->SetBranchStatus("mu2_jetNDauChargedMVASel",1);
   readtree->SetBranchStatus("ele1_charge",1);
   readtree->SetBranchStatus("ele1_jetNDauChargedMVASel",1);
   readtree->SetBranchStatus("ele1_nMissingHits",1);
   readtree->SetBranchStatus("ele2_charge",1);
   readtree->SetBranchStatus("ele2_jetNDauChargedMVASel",1);
   readtree->SetBranchStatus("ele2_nMissingHits",1);
   readtree->SetBranchStatus("mu1_PFRelIso04",1);
   readtree->SetBranchStatus("mu2_PFRelIso04",1);
   readtree->SetBranchStatus("ele1_PFRelIso04",1);
   readtree->SetBranchStatus("ele1_sigmaEtaEta",1);
   readtree->SetBranchStatus("ele1_HoE",1);
   readtree->SetBranchStatus("ele1_deltaEta",1);
   readtree->SetBranchStatus("ele1_deltaPhi",1);
   readtree->SetBranchStatus("ele1_OoEminusOoP",1);
   readtree->SetBranchStatus("ele2_PFRelIso04",1);
   readtree->SetBranchStatus("ele2_sigmaEtaEta",1);
   readtree->SetBranchStatus("ele2_HoE",1);
   readtree->SetBranchStatus("ele2_deltaEta",1);
   readtree->SetBranchStatus("ele2_deltaPhi",1);
   readtree->SetBranchStatus("ele2_OoEminusOoP",1);
   */
   readtree->SetBranchStatus("HiggsDecay",1);
   readtree->SetBranchStatus("tau1_pt",1);
   readtree->SetBranchStatus("tau1_eta",1);
   readtree->SetBranchStatus("tau1_phi",1);
   readtree->SetBranchStatus("tau1_E",1);
   readtree->SetBranchStatus("tau1_dxy",1);
   readtree->SetBranchStatus("tau1_dz",1);
   readtree->SetBranchStatus("tau1_byVLooseIsolationMVArun2v1DBdR03oldDMwLT",1);
   readtree->SetBranchStatus("tau1_byLooseIsolationMVArun2v1DBdR03oldDMwLT",1);
   readtree->SetBranchStatus("tau1_rawMVArun2v1DBdR03oldDMwLT",1);
   readtree->SetBranchStatus("tau1_decayModeFindingOldDMs",1);
   readtree->SetBranchStatus("tau2_pt",1);
   readtree->SetBranchStatus("tau2_eta",1);
   readtree->SetBranchStatus("tau2_phi",1);
   readtree->SetBranchStatus("tau2_E",1);
   readtree->SetBranchStatus("tau2_dxy",1);
   readtree->SetBranchStatus("tau2_dz",1);
   readtree->SetBranchStatus("tau2_byVLooseIsolationMVArun2v1DBdR03oldDMwLT",1);
   readtree->SetBranchStatus("tau2_byLooseIsolationMVArun2v1DBdR03oldDMwLT",1);
   readtree->SetBranchStatus("tau2_rawMVArun2v1DBdR03oldDMwLT",1);
   readtree->SetBranchStatus("tau2_decayModeFindingOldDMs",1);
   readtree->SetBranchStatus("jet8_pt",1);
   readtree->SetBranchStatus("jet8_eta",1);
   readtree->SetBranchStatus("jet8_phi",1);
   readtree->SetBranchStatus("jet8_E",1);
   readtree->SetBranchStatus("jet8_CSV",1);
   readtree->SetBranchStatus("jet7_pt",1);
   readtree->SetBranchStatus("jet7_eta",1);
   readtree->SetBranchStatus("jet7_phi",1);
   readtree->SetBranchStatus("jet7_E",1);
   readtree->SetBranchStatus("jet7_CSV",1);
   readtree->SetBranchStatus("jet6_pt",1);
   readtree->SetBranchStatus("jet6_eta",1);
   readtree->SetBranchStatus("jet6_phi",1);
   readtree->SetBranchStatus("jet6_E",1);
   readtree->SetBranchStatus("jet6_CSV",1);
   readtree->SetBranchStatus("jet5_pt",1);
   readtree->SetBranchStatus("jet5_eta",1);
   readtree->SetBranchStatus("jet5_phi",1);
   readtree->SetBranchStatus("jet5_E",1);
   readtree->SetBranchStatus("jet5_CSV",1);
   readtree->SetBranchStatus("jet4_pt",1);
   readtree->SetBranchStatus("jet4_eta",1);
   readtree->SetBranchStatus("jet4_phi",1);
   readtree->SetBranchStatus("jet4_E",1);
   readtree->SetBranchStatus("jet4_CSV",1);
   readtree->SetBranchStatus("jet1_pt",1);
   readtree->SetBranchStatus("jet1_eta",1);
   readtree->SetBranchStatus("jet1_phi",1);
   readtree->SetBranchStatus("jet1_E",1);
   readtree->SetBranchStatus("jet1_CSV",1);
   readtree->SetBranchStatus("jet2_pt",1);
   readtree->SetBranchStatus("jet2_eta",1);
   readtree->SetBranchStatus("jet2_phi",1);
   readtree->SetBranchStatus("jet2_E",1);
   readtree->SetBranchStatus("jet2_CSV",1);
   readtree->SetBranchStatus("jet3_pt",1);
   readtree->SetBranchStatus("jet3_eta",1);
   readtree->SetBranchStatus("jet3_phi",1);
   readtree->SetBranchStatus("jet3_E",1);
   readtree->SetBranchStatus("jet3_CSV",1);
   readtree->SetBranchStatus("PFMET",1);
   readtree->SetBranchStatus("PFMETphi",1);
   readtree->SetBranchStatus("MHT",1);
   readtree->SetBranchStatus("metLD",1);
   readtree->SetBranchStatus("mht",1);
   readtree->SetBranchStatus("mhtT",1);
   readtree->SetBranchStatus("mhtT_met",1);
   readtree->SetBranchStatus("mht_met",1);
   readtree->SetBranchStatus("lep1_conePt",1);
   readtree->SetBranchStatus("lep2_conePt",1);
   readtree->SetBranchStatus("lep3_conePt",1);
   readtree->SetBranchStatus("mindr_lep1_jet",1);
   readtree->SetBranchStatus("mindr_lep2_jet",1);
   readtree->SetBranchStatus("mindr_lep3_jet",1);
   readtree->SetBranchStatus("mT_lep1",1);
   readtree->SetBranchStatus("mT_lep2",1);
   readtree->SetBranchStatus("min_dr_lep_jet",1);
   readtree->SetBranchStatus("dr_leps",1);
   readtree->SetBranchStatus("max_lep_eta",1);
   readtree->SetBranchStatus("mbb",1);
   readtree->SetBranchStatus("mbb_loose",1);
   readtree->SetBranchStatus("Hj_tagger_resTop",1);
   readtree->SetBranchStatus("Hj_tagger_hadTop",1);
   readtree->SetBranchStatus("HTT",1);
   readtree->SetBranchStatus("nBJetLoose",1);
   readtree->SetBranchStatus("nBJetMedium",1);
   readtree->SetBranchStatus("FR_weight",1);
   readtree->SetBranchStatus("triggerSF_weight",1);
   readtree->SetBranchStatus("bTagSF_weight",1);
   readtree->SetBranchStatus("PU_weight",1);
   readtree->SetBranchStatus("MC_weight",1);
   readtree->SetBranchStatus("mvaOutput_2lss_ttV",1);
   readtree->SetBranchStatus("mvaOutput_2lss_ttbar",1);
   readtree->SetBranchStatus("avg_dr_jet",1);
   readtree->SetBranchStatus("nEvent",1);
   readtree->SetBranchStatus("ls",1);
   readtree->SetBranchStatus("run",1);
   readtree->SetBranchStatus("n_presel_mu",1);
   readtree->SetBranchStatus("n_fakeablesel_mu",1);
   readtree->SetBranchStatus("n_mvasel_mu",1);
   readtree->SetBranchStatus("n_presel_ele",1);
   readtree->SetBranchStatus("n_fakeablesel_ele",1);
   readtree->SetBranchStatus("n_mvasel_ele",1);
   readtree->SetBranchStatus("n_presel_tau",1);
   readtree->SetBranchStatus("n_presel_jet",1);
   readtree->SetBranchStatus("tau1_charge",1);
   readtree->SetBranchStatus("tau1_decayModeFindingOldDMs",1);
   readtree->SetBranchStatus("tau1_decayModeFindingNewDMs",1);
   readtree->SetBranchStatus("tau1_byLooseCombinedIsolationDeltaBetaCorr3Hits",1);
   readtree->SetBranchStatus("tau1_byMediumCombinedIsolationDeltaBetaCorr3Hits",1);
   readtree->SetBranchStatus("tau1_byTightCombinedIsolationDeltaBetaCorr3Hits",1);
   readtree->SetBranchStatus("tau1_byLooseCombinedIsolationDeltaBetaCorr3HitsdR03",1);
   readtree->SetBranchStatus("tau1_byMediumCombinedIsolationDeltaBetaCorr3HitsdR03",1);
   readtree->SetBranchStatus("tau1_byTightCombinedIsolationDeltaBetaCorr3HitsdR03",1);
   readtree->SetBranchStatus("tau1_byLooseIsolationMVArun2v1DBdR03oldDMwLT",1);
   readtree->SetBranchStatus("tau1_byMediumIsolationMVArun2v1DBdR03oldDMwLT",1);
   readtree->SetBranchStatus("tau1_byTightIsolationMVArun2v1DBdR03oldDMwLT",1);
   readtree->SetBranchStatus("tau1_byVTightIsolationMVArun2v1DBdR03oldDMwLT",1);
   readtree->SetBranchStatus("tau2_charge",1);
   readtree->SetBranchStatus("tau2_decayModeFindingOldDMs",1);
   readtree->SetBranchStatus("tau2_decayModeFindingNewDMs",1);
   readtree->SetBranchStatus("tau2_byLooseCombinedIsolationDeltaBetaCorr3Hits",1);
   readtree->SetBranchStatus("tau2_byMediumCombinedIsolationDeltaBetaCorr3Hits",1);
   readtree->SetBranchStatus("tau2_byTightCombinedIsolationDeltaBetaCorr3Hits",1);
   readtree->SetBranchStatus("tau2_byLooseCombinedIsolationDeltaBetaCorr3HitsdR03",1);
   readtree->SetBranchStatus("tau2_byMediumCombinedIsolationDeltaBetaCorr3HitsdR03",1);
   readtree->SetBranchStatus("tau2_byTightCombinedIsolationDeltaBetaCorr3HitsdR03",1);
   readtree->SetBranchStatus("tau2_byLooseIsolationMVArun2v1DBdR03oldDMwLT",1);
   readtree->SetBranchStatus("tau2_byMediumIsolationMVArun2v1DBdR03oldDMwLT",1);
   readtree->SetBranchStatus("tau2_byTightIsolationMVArun2v1DBdR03oldDMwLT",1);
   readtree->SetBranchStatus("tau2_byVTightIsolationMVArun2v1DBdR03oldDMwLT",1);
   readtree->SetBranchStatus("maxeta",1);
   readtree->SetBranchStatus("massL",1);
   readtree->SetBranchStatus("massll",1);
   readtree->SetBranchStatus("massL_SFOS",1);
   readtree->SetBranchStatus("mass_diele",1);
   readtree->SetBranchStatus("Bin2l",1);
   readtree->SetBranchStatus("SubCat2l",1);
   readtree->SetBranchStatus("Sum2lCharge",1);
   readtree->SetBranchStatus("Dilep_bestMVA",1);
   readtree->SetBranchStatus("Dilep_worseMVA",1);
   readtree->SetBranchStatus("Dilep_pdgId",1);
   readtree->SetBranchStatus("Dilep_htllv",1);
   readtree->SetBranchStatus("Dilep_mtWmin",1);
   readtree->SetBranchStatus("Dilep_nTight",1);
   readtree->SetBranchStatus("HighestJetCSV",1);
   readtree->SetBranchStatus("HtJet",1);
   readtree->SetBranchStatus("nBestVtx",1);
   readtree->SetBranchStatus("minMllAFAS",1);
   readtree->SetBranchStatus("minMllAFOS",1);
   readtree->SetBranchStatus("minMllSFOS",1);
   readtree->SetBranchStatus("leadLep_isMatchRightCharge",1);
   readtree->SetBranchStatus("leadLep_mcMatchId",1);
   readtree->SetBranchStatus("leadLep_isFromTop",1);
   readtree->SetBranchStatus("leadLep_isFromH",1);
   readtree->SetBranchStatus("leadLep_isFromB",1);
   readtree->SetBranchStatus("leadLep_isFromC",1);
   readtree->SetBranchStatus("leadLep_mcPromptGamma",1);
   readtree->SetBranchStatus("leadLep_mcPromptFS",1);
   readtree->SetBranchStatus("secondLep_isMatchRightCharge",1);
   readtree->SetBranchStatus("secondLep_mcMatchId",1);
   readtree->SetBranchStatus("secondLep_isFromTop",1);
   readtree->SetBranchStatus("secondLep_isFromH",1);
   readtree->SetBranchStatus("secondLep_isFromB",1);
   readtree->SetBranchStatus("secondLep_isFromC",1);
   readtree->SetBranchStatus("secondLep_mcPromptGamma",1);
   readtree->SetBranchStatus("secondLep_mcPromptFS",1);
   readtree->SetBranchStatus("Jet_numLoose",1);
   readtree->SetBranchStatus("leadLep_corrpt",1);
   readtree->SetBranchStatus("secondLep_corrpt",1);
   readtree->SetBranchStatus("leadLep_jetdr",1);
   readtree->SetBranchStatus("leadLep_jetcsv",1);
   readtree->SetBranchStatus("secondLep_jetdr",1);
   readtree->SetBranchStatus("secondLep_jetcsv",1);
   readtree->SetBranchStatus("Mt_metleadlep",1);
   readtree->SetBranchStatus("hadTop_BDT",1);
   readtree->SetBranchStatus("leadLep_BDT",1);
   readtree->SetBranchStatus("secondLep_BDT",1);
   readtree->SetBranchStatus("thirdLep_jetcsv",1);
   readtree->SetBranchStatus("nLepTight",1);
   readtree->SetBranchStatus("trueInteractions",1);
   readtree->SetBranchStatus("nLepFO",1);
   readtree->SetBranchStatus("resTop_BDT",1);
   //readtree->SetBranchStatus("Hj1_BDT",1);
   //if(skimType ==0){
   /*
       readtree->SetBranchStatus("HadTop_Dr_leph_bfromlTop",1);
       readtree->SetBranchStatus("HadTop_bjet_lepTop_csv",1);
       readtree->SetBranchStatus("HadTop_bjet_hadTop_csv",1);
       readtree->SetBranchStatus("HadTop_reco_hadTop_pt",1);
       readtree->SetBranchStatus("HadTop_reco_hadTop_mass",1);
       readtree->SetBranchStatus("HadTop_reco_WhadTop_mass",1);
       readtree->SetBranchStatus("HadTop_PtRatio_leptOverleph",1);
       readtree->SetBranchStatus("HadTop_Dr_lept_bfromlTop",1);
       readtree->SetBranchStatus("HadTop_Dr_lept_bfromhTop",1);
       readtree->SetBranchStatus("Jet25_isToptag",1);
       readtree->SetBranchStatus("bjet_resTop_index",1);
       readtree->SetBranchStatus("wjet1_resTop_index",1);
       readtree->SetBranchStatus("wjet2_resTop_index",1);
       readtree->SetBranchStatus("Jet25_isResToptag",1);
       readtree->SetBranchStatus("Jet25_axis2",1);
       readtree->SetBranchStatus("Jet25_qg",1);
       readtree->SetBranchStatus("Jet25_bDiscriminator",1);
       readtree->SetBranchStatus("Jet25_pfCombinedInclusiveSecondaryVertexV2BJetTags",1);
       readtree->SetBranchStatus("Jet25_pfCombinedMVAV2BJetTags",1);
       readtree->SetBranchStatus("Jet25_pfJetProbabilityBJetTags",1);
       readtree->SetBranchStatus("Jet25_pfDeepCSVCvsLJetTags",1);
       readtree->SetBranchStatus("Jet25_pfDeepCSVCvsBJetTags",1);
       readtree->SetBranchStatus("Jet25_ptD",1);
       readtree->SetBranchStatus("Jet25_mult",1);
       readtree->SetBranchStatus("Jet25_pfCombinedCvsLJetTags",1);
       readtree->SetBranchStatus("Jet25_pfCombinedCvsBJetTags",1);
       readtree->SetBranchStatus("Jet25_pt",1);
       readtree->SetBranchStatus("Jet25_eta",1);
       readtree->SetBranchStatus("Jet25_phi",1);
       readtree->SetBranchStatus("Jet25_energy",1);
       readtree->SetBranchStatus("Jet25_px",1);
       readtree->SetBranchStatus("Jet25_py",1);
       readtree->SetBranchStatus("Jet25_pz",1);
       readtree->SetBranchStatus("Jet25_mass",1);
       readtree->SetBranchStatus("Jet25_isFromH",1);
       readtree->SetBranchStatus("Jet25_isFromTop",1);
       readtree->SetBranchStatus("Jet25_matchId",1);
       readtree->SetBranchStatus("Jet25_neutralHadEnergyFraction",1);
       //readtree->SetBranchStatus("Jet25_neutralEmEnergyFraction",1);
       readtree->SetBranchStatus("Jet25_chargedHadronEnergyFraction",1);
       readtree->SetBranchStatus("Jet25_chargedEmEnergyFraction",1);
       readtree->SetBranchStatus("Jet25_muonEnergyFraction",1);
       readtree->SetBranchStatus("Jet25_electronEnergy",1);
       readtree->SetBranchStatus("Jet25_photonEnergy",1);
       //readtree->SetBranchStatus("Jet25_emEnergyFraction",1);
       readtree->SetBranchStatus("Jet25_numberOfConstituents",1);
       readtree->SetBranchStatus("Jet25_chargedMultiplicity",1);
       readtree->SetBranchStatus("Jet25_metptratio",1);
       readtree->SetBranchStatus("Jet25_dilepmetptratio",1);
       readtree->SetBranchStatus("Jet25_nonjdr",1);
       readtree->SetBranchStatus("Jet25_nonjdilepdr",1);
       readtree->SetBranchStatus("Jet25_lepdrmin",1);
       readtree->SetBranchStatus("Jet25_lepdrmax",1);
       readtree->SetBranchStatus("Jet25_dilepdr",1);
       readtree->SetBranchStatus("Jet25_bjdr",1);
       readtree->SetBranchStatus("Jet25_nonjdeta",1);
       readtree->SetBranchStatus("Jet25_nonjdilepdeta",1);
       readtree->SetBranchStatus("Jet25_lepdetamin",1);
       readtree->SetBranchStatus("Jet25_lepdetamax",1);
       readtree->SetBranchStatus("Jet25_dilepdeta",1);
       readtree->SetBranchStatus("Jet25_bjdeta",1);
       readtree->SetBranchStatus("Jet25_nonjdphi",1);
       readtree->SetBranchStatus("Jet25_nonjdilepdphi",1);
       readtree->SetBranchStatus("Jet25_lepdphimin",1);
       readtree->SetBranchStatus("Jet25_lepdphimax",1);
       readtree->SetBranchStatus("Jet25_dilepdphi",1);
       readtree->SetBranchStatus("Jet25_bjdphi",1);
       readtree->SetBranchStatus("Jet25_nonjptratio",1);
       readtree->SetBranchStatus("Jet25_nonjdilepptratio",1);
       readtree->SetBranchStatus("Jet25_lepptratiomin",1);
       readtree->SetBranchStatus("Jet25_lepptratiomax",1);
       readtree->SetBranchStatus("Jet25_dilepptratio",1);
       readtree->SetBranchStatus("Jet25_bjptratio",1);
       readtree->SetBranchStatus("FakeLep_corrpt",1);
       readtree->SetBranchStatus("FakeLep_ismvasel",1);
       readtree->SetBranchStatus("FakeLep_charge",1);
       readtree->SetBranchStatus("FakeLep_mvaId",1);
       readtree->SetBranchStatus("FakeLep_minIso",1);
       readtree->SetBranchStatus("FakeLep_minIsoCh",1);
       readtree->SetBranchStatus("FakeLep_minIsoNeu",1);
       readtree->SetBranchStatus("FakeLep_ptratio",1);
       readtree->SetBranchStatus("FakeLep_ptrel",1);
       readtree->SetBranchStatus("FakeLep_sig3d",1);
       readtree->SetBranchStatus("FakeLep_segment",1);
       readtree->SetBranchStatus("FakeLep_lostHits",1);
       readtree->SetBranchStatus("FakeLep_relIso04",1);
       readtree->SetBranchStatus("FakeLep_relIsoRhoEA",1);
       readtree->SetBranchStatus("FakeLep_TightCharge",1);
       readtree->SetBranchStatus("FakeLep_passConv",1);
       readtree->SetBranchStatus("FakeLep_jetdr",1);
       readtree->SetBranchStatus("FakeLep_jetCSV",1);
       readtree->SetBranchStatus("FakeLep_dxyAbs",1);
       readtree->SetBranchStatus("FakeLep_dz",1);
       readtree->SetBranchStatus("FakeLep_leptonMVA",1);
       readtree->SetBranchStatus("FakeLep_jetNDauChargedMVASel",1);
       readtree->SetBranchStatus("FakeLep_isFromB",1);
       readtree->SetBranchStatus("FakeLep_isFromC",1);
       readtree->SetBranchStatus("FakeLep_isFromH",1);
       readtree->SetBranchStatus("FakeLep_isFromTop",1);
       readtree->SetBranchStatus("FakeLep_matchId",1);
       readtree->SetBranchStatus("FakeLep_PdgId",1);
       readtree->SetBranchStatus("FakeLep_matchIndex",1);
       readtree->SetBranchStatus("FakeLep_pt",1);
       readtree->SetBranchStatus("FakeLep_eta",1);
       readtree->SetBranchStatus("FakeLep_phi",1);
       readtree->SetBranchStatus("FakeLep_energy",1);
   */
   //}
   readtree->SetBranchStatus("EventWeight",1);
   readtree->SetBranchStatus("EVENT_genWeight",1);
   //readtree->SetBranchStatus("EVENT_genWeights",1);
   readtree->SetBranchStatus("bWeight",1);
   readtree->SetBranchStatus("puWeight",1);
   readtree->SetBranchStatus("lepSF",1);
   readtree->SetBranchStatus("ChargeMis",1);
   readtree->SetBranchStatus("FakeRate",1);
   readtree->SetBranchStatus("TriggerSF",1);
   readtree->SetBranchStatus("puWeight_SysUp",1);
   readtree->SetBranchStatus("lepSF_SysUp",1);
   readtree->SetBranchStatus("ChargeMis_SysUp",1);
   //readtree->SetBranchStatus("FakeRate_SysUp",1);
   readtree->SetBranchStatus("TriggerSF_SysUp",1);
   readtree->SetBranchStatus("puWeight_SysDown",1);
   readtree->SetBranchStatus("lepSF_SysDown",1);
   readtree->SetBranchStatus("ChargeMis_SysDown",1);
   //readtree->SetBranchStatus("FakeRate_SysDown",1);
   readtree->SetBranchStatus("TriggerSF_SysDown",1);
   readtree->SetBranchStatus("bWeight_central",1);
   readtree->SetBranchStatus("bWeight_up_jes",1);
   readtree->SetBranchStatus("bWeight_up_lf",1);
   readtree->SetBranchStatus("bWeight_up_hf",1);
   readtree->SetBranchStatus("bWeight_up_hfstats1",1);
   readtree->SetBranchStatus("bWeight_up_hfstats2",1);
   readtree->SetBranchStatus("bWeight_up_lfstats1",1);
   readtree->SetBranchStatus("bWeight_up_lfstats2",1);
   readtree->SetBranchStatus("bWeight_up_cferr1",1);
   readtree->SetBranchStatus("bWeight_up_cferr2",1);
   readtree->SetBranchStatus("bWeight_down_jes",1);
   readtree->SetBranchStatus("bWeight_down_lf",1);
   readtree->SetBranchStatus("bWeight_down_hf",1);
   readtree->SetBranchStatus("bWeight_down_hfstats1",1);
   readtree->SetBranchStatus("bWeight_down_hfstats2",1);
   readtree->SetBranchStatus("bWeight_down_lfstats1",1);
   readtree->SetBranchStatus("bWeight_down_lfstats2",1);
   readtree->SetBranchStatus("bWeight_down_cferr1",1);
   readtree->SetBranchStatus("bWeight_down_cferr2",1);
   readtree->SetBranchStatus("TTHLep_3L",1);
   readtree->SetBranchStatus("Trig_1Ele",1);
   readtree->SetBranchStatus("Trig_2Ele",1);
   readtree->SetBranchStatus("Trig_3Ele",1);
   readtree->SetBranchStatus("Trig_1Mu",1);
   readtree->SetBranchStatus("Trig_1Mu1Ele",1);
   readtree->SetBranchStatus("Trig_1Mu2Ele",1);
   readtree->SetBranchStatus("Trig_2Mu",1);
   readtree->SetBranchStatus("Trig_2Mu1Ele",1);
   readtree->SetBranchStatus("Trig_3Mu",1);
   readtree->SetBranchStatus("Dilep_worseIso",1);
   readtree->SetBranchStatus("Dilep_worseSip",1);
   readtree->SetBranchStatus("mass3L",1);
   readtree->SetBranchStatus("Trilep_mtWmin",1);
   readtree->SetBranchStatus("SubCat3L",1);
   readtree->SetBranchStatus("Sum3LCharge",1);
   readtree->SetBranchStatus("Trilep_n_mu",1);
   readtree->SetBranchStatus("Trilep_nTight",1);
   readtree->SetBranchStatus("Trilep_n_ele",1);
   readtree->SetBranchStatus("Trilep_bestMVA",1);
   readtree->SetBranchStatus("Trilep_worseIso",1);
   readtree->SetBranchStatus("Trilep_worseMVA",1);
   readtree->SetBranchStatus("Trilep_worseSip",1);
   readtree->SetBranchStatus("Dilep_worsedz",1);
   readtree->SetBranchStatus("thirdLep_isMatchRightCharge",1);
   readtree->SetBranchStatus("thirdLep_mcMatchId",1);
   readtree->SetBranchStatus("thirdLep_isFromTop",1);
   readtree->SetBranchStatus("thirdLep_isFromH",1);
   readtree->SetBranchStatus("thirdLep_isFromB",1);
   readtree->SetBranchStatus("thirdLep_isFromC",1);
   readtree->SetBranchStatus("thirdLep_mcPromptGamma",1);
   readtree->SetBranchStatus("thirdLep_mcPromptFS",1);
   readtree->SetBranchStatus("lep3_BDT",1);
   readtree->SetBranchStatus("lep1_charge",1);
   readtree->SetBranchStatus("lep1_dxy",1);
   readtree->SetBranchStatus("lep1_dz",1);
   readtree->SetBranchStatus("lep1_mvaId",1);
   readtree->SetBranchStatus("lep1_eta",1);
   readtree->SetBranchStatus("lep1_minIso",1);
   readtree->SetBranchStatus("lep1_minIsoCh",1);
   readtree->SetBranchStatus("lep1_minIsoNeu",1);
   readtree->SetBranchStatus("lep1_pdgId",1);
   readtree->SetBranchStatus("lep1_pt",1);
   readtree->SetBranchStatus("lep1_phi",1);
   readtree->SetBranchStatus("lep1_ptratio",1);
   readtree->SetBranchStatus("lep1_ptrel",1);
   readtree->SetBranchStatus("lep1_segment",1);
   readtree->SetBranchStatus("lep1_sig3d",1);
   readtree->SetBranchStatus("lep1_lostHits",1);
   readtree->SetBranchStatus("lep1_relIso04",1);
   readtree->SetBranchStatus("lep1_relIso03",1);
   readtree->SetBranchStatus("lep1_TightCharge",1);
   readtree->SetBranchStatus("lep1_passConv",1);
   readtree->SetBranchStatus("lep2_charge",1);
   readtree->SetBranchStatus("lep2_dxy",1);
   readtree->SetBranchStatus("lep2_dz",1);
   readtree->SetBranchStatus("lep2_mvaId",1);
   readtree->SetBranchStatus("lep2_eta",1);
   readtree->SetBranchStatus("lep2_minIso",1);
   readtree->SetBranchStatus("lep2_minIsoCh",1);
   readtree->SetBranchStatus("lep2_minIsoNeu",1);
   readtree->SetBranchStatus("lep2_pdgId",1);
   readtree->SetBranchStatus("lep2_pt",1);
   readtree->SetBranchStatus("lep2_phi",1);
   readtree->SetBranchStatus("lep2_ptratio",1);
   readtree->SetBranchStatus("lep2_ptrel",1);
   readtree->SetBranchStatus("lep2_segment",1);
   readtree->SetBranchStatus("lep2_sig3d",1);
   readtree->SetBranchStatus("lep2_lostHits",1);
   readtree->SetBranchStatus("lep2_relIso04",1);
   readtree->SetBranchStatus("lep2_relIso03",1);
   readtree->SetBranchStatus("lep2_TightCharge",1);
   readtree->SetBranchStatus("lep2_passConv",1);
   readtree->SetBranchStatus("lep3_charge",1);
   readtree->SetBranchStatus("lep3_dxy",1);
   readtree->SetBranchStatus("lep3_dz",1);
   readtree->SetBranchStatus("lep3_mvaId",1);
   readtree->SetBranchStatus("lep3_eta",1);
   readtree->SetBranchStatus("lep3_minIso",1);
   readtree->SetBranchStatus("lep3_minIsoCh",1);
   readtree->SetBranchStatus("lep3_minIsoNeu",1);
   readtree->SetBranchStatus("lep3_pdgId",1);
   readtree->SetBranchStatus("lep3_pt",1);
   readtree->SetBranchStatus("lep3_phi",1);
   readtree->SetBranchStatus("lep3_ptratio",1);
   readtree->SetBranchStatus("lep3_ptrel",1);
   readtree->SetBranchStatus("lep3_segment",1);
   readtree->SetBranchStatus("lep3_sig3d",1);
   readtree->SetBranchStatus("lep3_lostHits",1);
   readtree->SetBranchStatus("lep3_relIso04",1);
   readtree->SetBranchStatus("lep3_relIso03",1);
   readtree->SetBranchStatus("lep3_TightCharge",1);
   readtree->SetBranchStatus("lep3_passConv",1);
   readtree->SetBranchStatus("lep1_E",1);
   readtree->SetBranchStatus("lep1_isfakeablesel",1);
   readtree->SetBranchStatus("lep1_ismvasel",1);
   readtree->SetBranchStatus("lep2_E",1);
   readtree->SetBranchStatus("lep2_isfakeablesel",1);
   readtree->SetBranchStatus("lep2_ismvasel",1);
   readtree->SetBranchStatus("lep3_E",1);
   readtree->SetBranchStatus("lep3_isfakeablesel",1);
   readtree->SetBranchStatus("lep3_ismvasel",1);
   readtree->SetBranchStatus("genWeight_muF2",1);
   readtree->SetBranchStatus("genWeight_muF0p5",1);
   readtree->SetBranchStatus("genWeight_muR2",1);
   readtree->SetBranchStatus("genWeight_muR0p5",1);
   readtree->SetBranchStatus("elelooseSF_SysUp",1);
   readtree->SetBranchStatus("elelooseSF",1);
   readtree->SetBranchStatus("elelooseSF_SysDown",1);
   readtree->SetBranchStatus("eletightSF_SysUp",1);
   readtree->SetBranchStatus("eletightSF",1);
   readtree->SetBranchStatus("eletightSF_SysDown",1);
   readtree->SetBranchStatus("mulooseSF_SysUp",1);
   readtree->SetBranchStatus("mulooseSF",1);
   readtree->SetBranchStatus("mulooseSF_SysDown",1);
   readtree->SetBranchStatus("mutightSF_SysUp",1);
   readtree->SetBranchStatus("mutightSF",1);
   readtree->SetBranchStatus("mutightSF_SysDown",1);
   readtree->SetBranchStatus("FakeRate_m_central",1);
   readtree->SetBranchStatus("FakeRate_m_up",1);
   readtree->SetBranchStatus("FakeRate_m_down",1);
   readtree->SetBranchStatus("FakeRate_m_pt1",1);
   readtree->SetBranchStatus("FakeRate_m_pt2",1);
   readtree->SetBranchStatus("FakeRate_m_be1",1);
   readtree->SetBranchStatus("FakeRate_m_be2",1);
   readtree->SetBranchStatus("FakeRate_m_QCD",1);
   readtree->SetBranchStatus("FakeRate_m_TT",1);
   readtree->SetBranchStatus("FakeRate_e_central",1);
   readtree->SetBranchStatus("FakeRate_e_up",1);
   readtree->SetBranchStatus("FakeRate_e_down",1);
   readtree->SetBranchStatus("FakeRate_e_pt1",1);
   readtree->SetBranchStatus("FakeRate_e_pt2",1);
   readtree->SetBranchStatus("FakeRate_e_be1",1);
   readtree->SetBranchStatus("FakeRate_e_be2",1);
   readtree->SetBranchStatus("FakeRate_e_QCD",1);
   readtree->SetBranchStatus("FakeRate_e_TT",1);
   // Hmass variables
   /*
   readtree->SetBranchStatus("Gen_pt",1);
   readtree->SetBranchStatus("Gen_eta",1);
   readtree->SetBranchStatus("Gen_phi",1);
   readtree->SetBranchStatus("Gen_energy",1);
   readtree->SetBranchStatus("Gen_pdg_id",1);
   readtree->SetBranchStatus("gen_lvTop_px",1);
   readtree->SetBranchStatus("gen_lvTop_py",1);
   readtree->SetBranchStatus("gen_lvTop_pz",1);
   readtree->SetBranchStatus("gen_lvTop_E",1);
   readtree->SetBranchStatus("gen_lvTop_Index",1);
   readtree->SetBranchStatus("gen_lvH_px",1);
   readtree->SetBranchStatus("gen_lvH_py",1);
   readtree->SetBranchStatus("gen_lvH_pz",1);
   readtree->SetBranchStatus("gen_lvH_E",1);
   readtree->SetBranchStatus("gen_lvH_Index",1);
   readtree->SetBranchStatus("gen_miss_px",1);
   readtree->SetBranchStatus("gen_miss_py",1);
   readtree->SetBranchStatus("Met_Fake_px",1);
   readtree->SetBranchStatus("Met_Fake_py",1);
   readtree->SetBranchStatus("Met_missFake_px",1);
   readtree->SetBranchStatus("Met_missFake_py",1);
   readtree->SetBranchStatus("n_leptons_fromH",1);
   readtree->SetBranchStatus("n_leptons_fromTop",1);
   readtree->SetBranchStatus("n_leptons_fromB",1);
   readtree->SetBranchStatus("n_jets_fromH",1);
   readtree->SetBranchStatus("n_jets_fromTop",1);
   readtree->SetBranchStatus("jjl_fromH_lvH_mass",1);
   readtree->SetBranchStatus("genWs_fromH_mass",1);
   readtree->SetBranchStatus("genWs_fromTop_mass",1);
   readtree->SetBranchStatus("genZs_fromH_mass",1);
   readtree->SetBranchStatus("genTaus_fromH_mass",1);
   readtree->SetBranchStatus("genWs_fromH_pt",1);
   readtree->SetBranchStatus("genWs_fromTop_pt",1);
   readtree->SetBranchStatus("genZs_fromH_pt",1);
   readtree->SetBranchStatus("genTaus_fromH_pt",1);
   readtree->SetBranchStatus("genWs_fromH_eta",1);
   readtree->SetBranchStatus("genWs_fromTop_eta",1);
   readtree->SetBranchStatus("genZs_fromH_eta",1);
   readtree->SetBranchStatus("genTaus_fromH_eta",1);
   readtree->SetBranchStatus("genWs_fromH_phi",1);
   readtree->SetBranchStatus("genWs_fromTop_phi",1);
   readtree->SetBranchStatus("genZs_fromH_phi",1);
   readtree->SetBranchStatus("genTaus_fromH_phi",1);
   readtree->SetBranchStatus("genWs_fromH_index",1);
   readtree->SetBranchStatus("genWs_fromTop_index",1);
   readtree->SetBranchStatus("genZs_fromH_index",1);
   readtree->SetBranchStatus("genTaus_fromH_index",1);
   readtree->SetBranchStatus("Gen_type1PF_px",1);
   readtree->SetBranchStatus("Gen_type1PF_py",1);
    */
};
