import sys, os, subprocess
import collections

varinfos = {
# copy
#"EVENT_event":{"type":"Long64_t","function":"copy"},
#"EVENT_genWeights":{"type":"Long64_t","function":"copy"},
#"EVENT_psWeights":{"type":"Long64_t","function":"copy"},
#"jet1_eta":{"type":"float","function":"copy"},
#"jet1_phi":{"type":"float","function":"copy"},
#"jet1_E":{"type":"float","function":"copy"},
#"jet1_DeepJet":{"type":"float","function":"copy"},
#"jet1_QGdiscr":{"type":"float","function":"copy"},
#"jet2_eta":{"type":"float","function":"copy"},
#"jet2_phi":{"type":"float","function":"copy"},
#"jet2_E":{"type":"float","function":"copy"},
#"jet2_DeepJet":{"type":"float","function":"copy"},
#"jet2_QGdiscr":{"type":"float","function":"copy"},
#"jet3_phi":{"type":"float","function":"copy"},
#"jet3_E":{"type":"float","function":"copy"},
#"jet3_DeepJet":{"type":"float","function":"copy"},
#"jet3_QGdiscr":{"type":"float","function":"copy"},
#"jet4_pt":{"type":"float","function":"copy"},
#"jet4_eta":{"type":"float","function":"copy"},
#"jet4_phi":{"type":"float","function":"copy"},
#"jet4_E":{"type":"float","function":"copy"},
#"jet4_DeepJet":{"type":"float","function":"copy"},
#"jet4_QGdiscr":{"type":"float","function":"copy"},
#"jetFwd1_pt":{"type":"float","function":"copy"},
#"jetFwd1_phi":{"type":"float","function":"copy"},
#"jetFwd1_E":{"type":"float","function":"copy"},
#"jetFwd2_pt":{"type":"float","function":"copy"},
#"jetFwd2_eta":{"type":"float","function":"copy"},
#"jetFwd2_phi":{"type":"float","function":"copy"},
#"jetFwd2_E":{"type":"float","function":"copy"},
#"jetFwd3_pt":{"type":"float","function":"copy"},
#"jetFwd3_eta":{"type":"float","function":"copy"},
#"jetFwd3_phi":{"type":"float","function":"copy"},
#"jetFwd3_E":{"type":"float","function":"copy"},
#"jetFwd4_pt":{"type":"float","function":"copy"},
#"jetFwd4_eta":{"type":"float","function":"copy"},
#"jetFwd4_phi":{"type":"float","function":"copy"},
#"jetFwd4_E":{"type":"float","function":"copy"},
#"PFMET":{"type":"float","function":"copy"},
#"PFMETphi":{"type":"float","function":"copy"},
#"MHT":{"type":"float","function":"copy"},
#"metLD":{"type":"float","function":"copy"},
#"lep1_conePt":{"type":"float","function":"copy"},
#"lep1_phi":{"type":"float","function":"copy"},
#"lep1_E":{"type":"float","function":"copy"},
#"lep2_conePt":{"type":"float","function":"copy"},
#"lep2_eta":{"type":"float","function":"copy"},
#"lep2_phi":{"type":"float","function":"copy"},
#"lep2_E":{"type":"float","function":"copy"},
#"lep3_conePt":{"type":"float","function":"copy"},
#"lep3_eta":{"type":"float","function":"copy"},
#"lep3_phi":{"type":"float","function":"copy"},
#"lep3_E":{"type":"float","function":"copy"},
#"mindr_lep1_jet":{"type":"float","function":"copy"},
#"mindr_lep2_jet":{"type":"float","function":"copy"},
#"mindr_lep3_jet":{"type":"float","function":"copy"},
#"mT_lep2":{"type":"float","function":"copy"},
#"min_dr_lep_jet":{"type":"float","function":"copy"},
#"dr_leps":{"type":"float","function":"copy"},
#"max_lep_eta":{"type":"float","function":"copy"},
#"mbb":{"type":"float","function":"copy"},
#"mbb_loose":{"type":"float","function":"copy"},
#"hadTop_BDT":{"type":"float","function":"copy"},
#"hadTop_pt":{"type":"float","function":"copy"},
#"Hj_tagger_hadTop":{"type":"float","function":"copy"},
#"nBJetLoose":{"type":"float","function":"copy"},
#"nBJetMedium":{"type":"float","function":"copy"},
#"FR_weight":{"type":"float","function":"copy"},
#"leptonSF_weight":{"type":"float","function":"copy"},
#"triggerSF_weight":{"type":"float","function":"copy"},
#"bTagSF_weight":{"type":"float","function":"copy"},
#"PU_weight":{"type":"float","function":"copy"},
#"MC_weight":{"type":"float","function":"copy"},
#"mvaOutput_2lss_ttbar":{"type":"float","function":"copy"},
#"mvaOutput_2lss_ttV":{"type":"float","function":"copy"},
#"avg_dr_jet":{"type":"float","function":"copy"},
#"n_presel_mu":{"type":"float","function":"copy"},
#"n_fakeablesel_mu":{"type":"float","function":"copy"},
#"n_mvasel_mu":{"type":"float","function":"copy"},
#"n_presel_ele":{"type":"float","function":"copy"},
#"n_fakeablesel_ele":{"type":"float","function":"copy"},
#"n_mvasel_ele":{"type":"float","function":"copy"},
#"n_presel_tau":{"type":"float","function":"copy"},
#"n_presel_jet":{"type":"float","function":"copy"},
#"n_presel_jetFwd":{"type":"float","function":"copy"},
#"nLightJet":{"type":"float","function":"copy"},
#"SourceNumber":{"type":"float","function":"copy"},
#"Bin2l":{"type":"float","function":"copy"},
#"DataEra":{"type":"float","function":"copy"},
#"TTHLep_2L":{"type":"float","function":"copy"},
#"TTHLep_2Ele":{"type":"float","function":"copy"},
#"TTHLep_2Mu":{"type":"float","function":"copy"},
#"TTHLep_MuEle":{"type":"float","function":"copy"},
#"TTHLep_3L":{"type":"float","function":"copy"},
#"Trig_1Ele":{"type":"float","function":"copy"},
#"Trig_2Ele":{"type":"float","function":"copy"},
#"Trig_3Ele":{"type":"float","function":"copy"},
#"Trig_1Mu":{"type":"float","function":"copy"},
#"Trig_1Mu1Ele":{"type":"float","function":"copy"},
#"Trig_1Mu2Ele":{"type":"float","function":"copy"},
#"Trig_2Mu":{"type":"float","function":"copy"},
#"Trig_2Mu1Ele":{"type":"float","function":"copy"},
#"Trig_3Mu":{"type":"float","function":"copy"},
#"SubCat2l":{"type":"float","function":"copy"},
#"massl":{"type":"float","function":"copy"},
#"massL":{"type":"float","function":"copy"},
#"mass_diele":{"type":"float","function":"copy"},
#"mass_dilep":{"type":"float","function":"copy"},
#"mass_dillep":{"type":"float","function":"copy"},
#"massL_SFOS":{"type":"float","function":"copy"},
#"mht":{"type":"float","function":"copy"},
#"mhtT":{"type":"float","function":"copy"},
#"mht_met":{"type":"float","function":"copy"},
#"mhtT_met":{"type":"float","function":"copy"},
#"leadLep_jetcsv":{"type":"float","function":"copy"},
#"leadLep_BDT":{"type":"float","function":"copy"},
#"secondLep_jetcsv":{"type":"float","function":"copy"},
#"secondLep_BDT":{"type":"float","function":"copy"},
#"maxeta":{"type":"float","function":"copy"},
#"massll":{"type":"float","function":"copy"},
#"massLT":{"type":"float","function":"copy"},
#"Sum2lCharge":{"type":"float","function":"copy"},
#"Dilep_bestMVA":{"type":"float","function":"copy"},
#"Dilep_worseMVA":{"type":"float","function":"copy"},
#"Dilep_pdgId":{"type":"float","function":"copy"},
#"nElectron":{"type":"float","function":"copy"},
#"Dilep_htllv":{"type":"float","function":"copy"},
#"Dilep_mtWmin":{"type":"float","function":"copy"},
#"Dilep_nTight":{"type":"float","function":"copy"},
#"HighestJetCSV":{"type":"float","function":"copy"},
#"HtJet":{"type":"float","function":"copy"},
#"nLepTight":{"type":"float","function":"copy"},
#"minMllAFAS":{"type":"float","function":"copy"},
#"minMllAFOS":{"type":"float","function":"copy"},
#"minMllSFOS":{"type":"float","function":"copy"},
#"min_Deta_leadfwdJet_jet":{"type":"float","function":"copy"},
#"min_Deta_mostfwdJet_jet":{"type":"float","function":"copy"},
#"mT2_top_3particle":{"type":"float","function":"copy"},
#"mT2_top_2particle":{"type":"float","function":"copy"},
#"mT2_W":{"type":"float","function":"copy"},
#"angle_bbpp_truth2l2b":{"type":"float","function":"copy"},
#"angle_bbpp_loose2b":{"type":"float","function":"copy"},
#"angle_bbpp_highest2b":{"type":"float","function":"copy"},
#"Hj_tagger":{"type":"float","function":"copy"},
#"HTT":{"type":"float","function":"copy"},
#"Dilep_worseIso":{"type":"float","function":"copy"},
#"Dilep_worseSip":{"type":"float","function":"copy"},
#"mass3L":{"type":"float","function":"copy"},
#"Trilep_mtWmin":{"type":"float","function":"copy"},
#"Sum3LCharge":{"type":"float","function":"copy"},
#"Trilep_n_mu":{"type":"float","function":"copy"},
#"Trilep_nTight":{"type":"float","function":"copy"},
#"Trilep_n_ele":{"type":"float","function":"copy"},
#"Trilep_bestMVA":{"type":"float","function":"copy"},
#"Trilep_worseIso":{"type":"float","function":"copy"},
#"Trilep_worseMVA":{"type":"float","function":"copy"},
#"Trilep_worseSip":{"type":"float","function":"copy"},
#"Dilep_worsedz":{"type":"float","function":"copy"},
#"lep3_BDT":{"type":"float","function":"copy"},
#"lep1_charge":{"type":"float","function":"copy"},
#"lep1_dxy":{"type":"float","function":"copy"},
#"lep1_dz":{"type":"float","function":"copy"},
#"lep1_mvaId":{"type":"float","function":"copy"},
#"lep1_minIso":{"type":"float","function":"copy"},
#"lep1_minIsoCh":{"type":"float","function":"copy"},
#"lep1_minIsoNeu":{"type":"float","function":"copy"},
#"lep1_pdgId":{"type":"float","function":"copy"},
#"lep1_ptratio":{"type":"float","function":"copy"},
#"lep1_ptrel":{"type":"float","function":"copy"},
#"lep1_segment":{"type":"float","function":"copy"},
#"lep1_sig3d":{"type":"float","function":"copy"},
#"lep1_lostHits":{"type":"float","function":"copy"},
#"lep1_relIso04":{"type":"float","function":"copy"},
#"lep1_relIso03":{"type":"float","function":"copy"},
#"lep1_TightCharge":{"type":"float","function":"copy"},
#"lep1_passConv":{"type":"float","function":"copy"},
#"lep2_charge":{"type":"float","function":"copy"},
#"lep2_dxy":{"type":"float","function":"copy"},
#"lep2_dz":{"type":"float","function":"copy"},
#"lep2_mvaId":{"type":"float","function":"copy"},
#"lep2_minIso":{"type":"float","function":"copy"},
#"lep2_minIsoCh":{"type":"float","function":"copy"},
#"lep2_minIsoNeu":{"type":"float","function":"copy"},
#"lep2_pdgId":{"type":"float","function":"copy"},
#"lep2_ptratio":{"type":"float","function":"copy"},
#"lep2_ptrel":{"type":"float","function":"copy"},
#"lep2_segment":{"type":"float","function":"copy"},
#"lep2_sig3d":{"type":"float","function":"copy"},
#"lep2_lostHits":{"type":"float","function":"copy"},
#"lep2_relIso04":{"type":"float","function":"copy"},
#"lep2_relIso03":{"type":"float","function":"copy"},
#"lep2_TightCharge":{"type":"float","function":"copy"},
#"lep2_passConv":{"type":"float","function":"copy"},
#"lep3_charge":{"type":"float","function":"copy"},
#"lep3_dxy":{"type":"float","function":"copy"},
#"lep3_dz":{"type":"float","function":"copy"},
#"lep3_mvaId":{"type":"float","function":"copy"},
#"lep3_minIso":{"type":"float","function":"copy"},
#"lep3_minIsoCh":{"type":"float","function":"copy"},
#"lep3_minIsoNeu":{"type":"float","function":"copy"},
#"lep3_pdgId":{"type":"float","function":"copy"},
#"lep3_ptratio":{"type":"float","function":"copy"},
#"lep3_ptrel":{"type":"float","function":"copy"},
#"lep3_segment":{"type":"float","function":"copy"},
#"lep3_sig3d":{"type":"float","function":"copy"},
#"lep3_lostHits":{"type":"float","function":"copy"},
#"lep3_relIso04":{"type":"float","function":"copy"},
#"lep3_relIso03":{"type":"float","function":"copy"},
#"lep3_TightCharge":{"type":"float","function":"copy"},
#"lep3_passConv":{"type":"float","function":"copy"},
#"lep1_isfakeablesel":{"type":"float","function":"copy"},
#"lep1_ismvasel":{"type":"float","function":"copy"},
#"lep2_isfakeablesel":{"type":"float","function":"copy"},
#"lep2_ismvasel":{"type":"float","function":"copy"},
#"lep3_isfakeablesel":{"type":"float","function":"copy"},
#"lep3_ismvasel":{"type":"float","function":"copy"},
#"genWeight_muF2":{"type":"float","function":"copy"},
#"genWeight_muF0p5":{"type":"float","function":"copy"},
#"genWeight_muR2":{"type":"float","function":"copy"},
#"genWeight_muR0p5":{"type":"float","function":"copy"},
#"isSFOS_metLD":{"type":"float","function":"copy"},
#"nLep_Cat":{"type":"float","function":"copy"},
#"nBestVtx":{"type":"float","function":"copy"},
#"trueInteractions":{"type":"double","function":"copy"},
#"EVENT_genWeight":{"type":"float","function":"copy"},
#"bWeight":{"type":"float","function":"copy"},
#"puWeight":{"type":"float","function":"copy"},
#"lepSF":{"type":"float","function":"copy"},
#"ChargeMis":{"type":"float","function":"copy"},
#"FakeRate":{"type":"float","function":"copy"},
#"Prefire":{"type":"float","function":"copy"},
#"puWeight_SysUp":{"type":"float","function":"copy"},
#"puWeight_SysDown":{"type":"float","function":"copy"},
#"lepSF_SysUp":{"type":"float","function":"copy"},
#"lepSF_SysDown":{"type":"float","function":"copy"},
#"ChargeMis_SysUp":{"type":"float","function":"copy"},
#"ChargeMis_SysDown":{"type":"float","function":"copy"},
#"TriggerSF":{"type":"float","function":"copy"},
#"TriggerSF_SysUp":{"type":"float","function":"copy"},
#"TriggerSF_SysDown":{"type":"float","function":"copy"},
#"Prefire_SysUp":{"type":"float","function":"copy"},
#"Prefire_SysDown":{"type":"float","function":"copy"},
#"elelooseSF":{"type":"float","function":"copy"},
#"elelooseSF_SysUp":{"type":"float","function":"copy"},
#"elelooseSF_SysDown":{"type":"float","function":"copy"},
#"eletightSF":{"type":"float","function":"copy"},
#"eletightSF_SysUp":{"type":"float","function":"copy"},
#"eletightSF_SysDown":{"type":"float","function":"copy"},
#"mulooseSF":{"type":"float","function":"copy"},
#"mulooseSF_SysUp":{"type":"float","function":"copy"},
#"mulooseSF_SysDown":{"type":"float","function":"copy"},
#"mutightSF":{"type":"float","function":"copy"},
#"mutightSF_SysUp":{"type":"float","function":"copy"},
#"mutightSF_SysDown":{"type":"float","function":"copy"},
#"bWeight_central":{"type":"float","function":"copy"},
#"bWeight_up_jes":{"type":"float","function":"copy"},
#"bWeight_up_lf":{"type":"float","function":"copy"},
#"bWeight_up_hf":{"type":"float","function":"copy"},
#"bWeight_up_hfstats1":{"type":"float","function":"copy"},
#"bWeight_up_hfstats2":{"type":"float","function":"copy"},
#"bWeight_up_lfstats1":{"type":"float","function":"copy"},
#"bWeight_up_lfstats2":{"type":"float","function":"copy"},
#"bWeight_up_cferr1":{"type":"float","function":"copy"},
#"bWeight_up_cferr2":{"type":"float","function":"copy"},
#"bWeight_down_jes":{"type":"float","function":"copy"},
#"bWeight_down_lf":{"type":"float","function":"copy"},
#"bWeight_down_hf":{"type":"float","function":"copy"},
#"bWeight_down_hfstats1":{"type":"float","function":"copy"},
#"bWeight_down_hfstats2":{"type":"float","function":"copy"},
#"bWeight_down_lfstats1":{"type":"float","function":"copy"},
#"bWeight_down_lfstats2":{"type":"float","function":"copy"},
#"bWeight_down_cferr1":{"type":"float","function":"copy"},
#"bWeight_down_cferr2":{"type":"float","function":"copy"},
#"FakeRate_m_central":{"type":"float","function":"copy"},
#"FakeRate_m_up":{"type":"float","function":"copy"},
#"FakeRate_m_down":{"type":"float","function":"copy"},
#"FakeRate_m_pt1":{"type":"float","function":"copy"},
#"FakeRate_m_pt2":{"type":"float","function":"copy"},
#"FakeRate_m_be1":{"type":"float","function":"copy"},
#"FakeRate_m_be2":{"type":"float","function":"copy"},
#"FakeRate_m_QCD":{"type":"float","function":"copy"},
#"FakeRate_m_TT":{"type":"float","function":"copy"},
#"FakeRate_e_central":{"type":"float","function":"copy"},
#"FakeRate_e_up":{"type":"float","function":"copy"},
#"FakeRate_e_down":{"type":"float","function":"copy"},
#"FakeRate_e_pt1":{"type":"float","function":"copy"},
#"FakeRate_e_pt2":{"type":"float","function":"copy"},
#"FakeRate_e_be1":{"type":"float","function":"copy"},
#"FakeRate_e_be2":{"type":"float","function":"copy"},
#"FakeRate_e_QCD":{"type":"float","function":"copy"},
#"FakeRate_e_TT":{"type":"float","function":"copy"},
#
#"Jet25_pt":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_bDiscriminator":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_eta":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_phi":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_energy":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_mass":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_px":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_py":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_qg":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_lepdrmin":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_lepdrmax":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_lepdphimin":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_lepdphimax":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_lepdetamin":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_lepdetamax":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_isToptag":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_isFromH":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_isFromTop":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_isFromLepTop":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_isLooseBdisc":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_isMediumBdisc":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_isTightBdisc":{"type":"std::vector<double>*","function":"copy"},
#"Jet25_matchId":{"type":"std::vector<double>*","function":"copy"},
#
## use
#### always
#"EventWeight":{"type":"float","function":"use"},
#"EVENT_rWeights":{"type":"std::vector<double>*","function":"use"},
#"nEvent":{"type":"int","function":"use"},
#"ls":{"type":"int","function":"use"},
#"run":{"type":"int","function":"use"},
#"leadLep_isMatchRightCharge":{"type":"float","function":"use"},
#"leadLep_mcMatchId":{"type":"float","function":"use"},
#"leadLep_isFromTop":{"type":"float","function":"use"},
#"leadLep_isFromH":{"type":"float","function":"use"},
#"leadLep_isFromZWH":{"type":"float","function":"use"},
#"leadLep_isFromB":{"type":"float","function":"use"},
#"leadLep_isFromC":{"type":"float","function":"use"},
#"leadLep_mcPromptGamma":{"type":"float","function":"use"},
#"leadLep_mcPromptFS":{"type":"float","function":"use"},
#"secondLep_isMatchRightCharge":{"type":"float","function":"use"},
#"secondLep_mcMatchId":{"type":"float","function":"use"},
#"secondLep_isFromTop":{"type":"float","function":"use"},
#"secondLep_isFromH":{"type":"float","function":"use"},
#"secondLep_isFromZWH":{"type":"float","function":"use"},
#"secondLep_isFromB":{"type":"float","function":"use"},
#"secondLep_isFromC":{"type":"float","function":"use"},
#"secondLep_mcPromptGamma":{"type":"float","function":"use"},
#"secondLep_mcPromptFS":{"type":"float","function":"use"},
#"thirdLep_isMatchRightCharge":{"type":"float","function":"use"},
#"thirdLep_mcMatchId":{"type":"float","function":"use"},
#"thirdLep_isFromTop":{"type":"float","function":"use"},
#"thirdLep_isFromH":{"type":"float","function":"use"},
#"thirdLep_isFromZWH":{"type":"float","function":"use"},
#"thirdLep_isFromB":{"type":"float","function":"use"},
#"thirdLep_isFromC":{"type":"float","function":"use"},
#"thirdLep_mcPromptGamma":{"type":"float","function":"use"},
#"thirdLep_mcPromptFS":{"type":"float","function":"use"},
#"fourthLep_isMatchRightCharge":{"type":"float","function":"use"},
#"fourthLep_mcMatchId":{"type":"float","function":"use"},
#"fourthLep_isFromTop":{"type":"float","function":"use"},
#"fourthLep_isFromH":{"type":"float","function":"use"},
#"fourthLep_isFromZWH":{"type":"float","function":"use"},
#"fourthLep_isFromB":{"type":"float","function":"use"},
#"fourthLep_isFromC":{"type":"float","function":"use"},
#"fourthLep_mcPromptGamma":{"type":"float","function":"use"},
#"fourthLep_mcPromptFS":{"type":"float","function":"use"},
#"isDiLepSR":{"type":"float","function":"use"},
#"isDiLepOS":{"type":"float","function":"use"},
#"isDiLepFake":{"type":"float","function":"use"},
#"isttWctrlSR":{"type":"float","function":"use"},
#"isttWctrlOS":{"type":"float","function":"use"},
#"isttWctrlFake":{"type":"float","function":"use"},
#"isTriLepSR":{"type":"float","function":"use"},
#"isTriLepFake":{"type":"float","function":"use"},
#"isWZctrlSR":{"type":"float","function":"use"},
#"isWZctrlFake":{"type":"float","function":"use"},
#"isttZctrlSR":{"type":"float","function":"use"},
#"isttZctrlFake":{"type":"float","function":"use"},
#"isZZctrlSR":{"type":"float","function":"use"},
#"isZZctrlFake":{"type":"float","function":"use"},
#"isQuaLepSR":{"type":"float","function":"use"},
#"isQuaLepFake":{"type":"float","function":"use"},
#"istHlikeDiLepSR":{"type":"float","function":"use"},
#"istHlikeDiLepOS":{"type":"float","function":"use"},
#"istHlikeDiLepFake":{"type":"float","function":"use"},
#"istHlikeTriLepSR":{"type":"float","function":"use"},
#"istHlikeTriLepFake":{"type":"float","function":"use"},
#"istHlikeQuaLepSR":{"type":"float","function":"use"},
#"istHlikeQuaLepFake":{"type":"float","function":"use"},
#"HiggsDecay":{"type":"int","function":"use"},

## NN 
"jet3_pt":{"type":"float","function":"use"},
"jet3_eta":{"type":"float","function":"use"},
"lep1_eta":{"type":"float","function":"use"},
"jet2_pt":{"type":"float","function":"use"},
"jet1_pt":{"type":"float","function":"use"},
"jetFwd1_eta":{"type":"float","function":"use"},
"mT_lep1":{"type":"float","function":"use"},
"resTop_BDT":{"type":"float","function":"use"},
"jet4_phi":{"type":"float","function":"use"},
"lep2_conePt":{"type":"float","function":"use"},
"mass_dilep":{"type":"float","function":"use"},
"jet1_phi":{"type":"float","function":"use"},
"jet2_eta":{"type":"float","function":"use"},
"n_presel_jetFwd":{"type":"float","function":"use"},
"n_presel_jet":{"type":"float","function":"use"},
"lep1_charge":{"type":"float","function":"use"},
"avg_dr_jet":{"type":"float","function":"use"},
"lep1_phi":{"type":"float","function":"use"},
"nBJetLoose":{"type":"float","function":"use"},
"jet4_pt":{"type":"float","function":"use"},
"mindr_lep1_jet":{"type":"float","function":"use"},
"mindr_lep2_jet":{"type":"float","function":"use"},
"lep1_conePt":{"type":"float","function":"use"},
"jetFwd1_pt":{"type":"float","function":"use"},
"lep2_phi":{"type":"float","function":"use"},
"jet2_phi":{"type":"float","function":"use"},
"lep2_eta":{"type":"float","function":"use"},
"mbb":{"type":"float","function":"use"},
"jet4_eta":{"type":"float","function":"use"},
"nBJetMedium":{"type":"float","function":"use"},
"Hj_tagger_resTop":{"type":"float","function":"use"},
"Dilep_pdgId":{"type":"float","function":"use"},
"mT_lep2":{"type":"float","function":"use"},
"metLD":{"type":"float","function":"use"},
"jet3_phi":{"type":"float","function":"use"},
"maxeta":{"type":"float","function":"use"},
"jet1_eta":{"type":"float","function":"use"},

# new
#"is_tH_like_and_not_ttH_like":{"type":"float","function":"new"},
#"cpodd_rwgt":{"type":"float","function":"new"},
#"xsec_rwgt":{"type":"float","function":"new"},
## NN vars
#"DNN_maxval":{"type":"float","function":"new"},
#"DNNCat":{"type":"float","function":"new"},
#"DNNSubCat1_option1":{"type":"float","function":"new"},
#"DNNSubCat2_option1":{"type":"float","function":"new"},
#"DNN_ttHnode_all":{"type":"float","function":"new"},
#"DNN_Restnode_all":{"type":"float","function":"new"},
#"DNN_ttWnode_all":{"type":"float","function":"new"},
#"DNN_tHQnode_all":{"type":"float","function":"new"},

}


var_infos = collections.OrderedDict(sorted(varinfos.items()))

# set branch status if function is not new
for var, info in var_infos.items():
    if not info["function"]=="new":
        print ('    readtree->SetBranchStatus("%s",1);'%var)

print ('\n\n  SetBranchStatus done \n')

# set branchaddress if function is use
for var, info in var_infos.items():
    if info["function"]=="use":
        print ('    oldtree->SetBranchAddress("%s",&%s);'%(var,var))

print ('\n\n  SetBranchAddress done \n')

# declare variable if function is not copy
for var, info in var_infos.items():
    if not info["function"]=="copy":
        print ('    %s %s = 0;'%(info["type"],var))

print ('\n\n  variable declaration done \n')

# clear variable if function is not copy
for var, info in var_infos.items():
    if not info["function"]=="copy":
        if info["type"].find("vector")>=0:
            print ('        %s->clear();'%var)
        else:
            print ('        %s = -9;'%var)

print ('\n\n  variable clear done \n')


# set newBranch if function is new
for var, info in var_infos.items():
    if info["function"]=="new":
        print ('    newtree->Branch("%s",&%s);'%(var,var))

print ('\n\n  set newtree branch done \n')


# nn vars
for var, info in var_infos.items():
    print ('            inputs["%s"]=%s;'%(var,var))



